version: 2
jobs:
  # Checkout code from Github, Install, & cache deps/devDeps.
  checkout_code:
    docker:
      - image: circleci/node:8.11-browsers
    working_directory: ~/vue-circleci
    steps:
      - checkout
      - attach_workspace:
          at: ~/vue-circleci
      - restore_cache:
          keys:
            - dependency-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - dependency-cache-{{ .Branch }}
            - dependency-cache-
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths: node_modules
      - persist_to_workspace:
          root: .
          paths: .
  # Run Eslint.
  linting:
    docker:
      - image: circleci/node:8.11-browsers
    working_directory: ~/vue-circleci
    steps:
      - attach_workspace:
          at: ~/vue-circleci
      - run: npm run lint
  # Run Jest Unit Tests
  unit_tests:
    docker:
      - image: circleci/node:8.11-browsers
    working_directory: ~/vue-circleci
    steps:
      - attach_workspace:
          at: ~/vue-circleci
      - run: npm run unit
      - store_artifacts:
          path: ./coverage/clover.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: ./coverage/clover.xml
  # Run NightWatch End-2-End Tests
  e2e_tests:
    docker:
      - image: circleci/node:8.11-browsers
    working_directory: ~/vue-circleci
    steps:
      - attach_workspace:
          at: ~/vue-circleci
      - run: mkdir e2e-reports
      - run:
          name: Download Selenium
          command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Start Selenium
          command: java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
          background: true
      - run: npm run e2e
      - store_artifacts:
          path: e2e-reports/
      - store_test_results:
          path: e2e-reports/
  # Build the project
  build:
    docker:
      - image: circleci/node:8.11-browsers
    working_directory: ~/vue-circleci
    steps:
      - attach_workspace:
          at: ~/vue-circleci
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths: .
  # Deploy the project using Now.
  deployment:
    docker:
      - image: circleci/node:8.11-browsers
    working_directory: ~/vue-circleci
    steps:
      - attach_workspace:
          at: ~/vue-circleci
      - run: sudo npm i -g --unsafe-perm now
      - deploy:
          name: Deploy & Alias
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              url=$(now dist -t ${NOW_TOKEN} -n=vue-circleci --static 2>/dev/null)
              echo "Site deployed to ${url}."
              echo $url
              now alias -t ${NOW_TOKEN} $url "vue-circleci"
              echo "${url} aliased to https://vue-circleci.now.sh"
            elif [ "${CIRCLE_BRANCH}" == "development" ]; then
              url=$(now dist -t ${NOW_TOKEN} -n=vue-circleci --static 2>/dev/null)
              echo "Site deployed to ${url}."
              now -t ${NOW_TOKEN} alias $url "vue-circleci-beta"
              echo "${url} aliased to https://vue-circleci-beta.now.sh"
            else
              echo "This failed miserably!"
            fi
workflows:
  version: 2
  test_and_build:
    jobs:
      - checkout_code
      - linting:
          requires:
            - checkout_code
      - unit_tests:
          requires:
            - checkout_code
      - e2e_tests:
          requires:
            - checkout_code
      - build:
          requires:
            - linting
            - unit_tests
            - e2e_tests
          filters:
            branches:
              only:
                - develop
                - master
      - deployment:
          requires:
            - build
          filters:
            branches:
              only:
                - master
